apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datakube
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    chart: spark-operator
    targetRevision: 1.0.5
    helm:
      valueFiles:
        - values.yaml
      values: |
        serviceAccounts:
          spark:
            create: true
            name: spark
          sparkoperator:
            create: true
            name: sparkoperator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
